### ISSUE TITLE
question about Replace the ml-agents library with our ml-agents.

### ISSUE THREAD

**Issue by vxgu86** [dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R#2] opened 2019-05-04 09:00 UTC
Wondering about the 
2. Replace the ml-agents library (in the virtual environment created during ML-Agents toolkit installation) with our ml-agents.
which ml-agents to replace and replace with which ?

thanks

**Comment by dtransposed** [comment] 2019-05-06 09:58
When you follow the official ML-Agents toolkit installation from Unity, at some point you are instructed to install ml-agents library in your virtual environment. You should replace it's contents with my custom environment from the repo.

**Comment by dtransposed** [comment] 2019-05-09 11:30
I hope that the problem is resolved. I am closing this issue.

**Closed as completed by dtransposed** 2019-05-09 11:30 UTC

**Comment by vxgu86** [comment] 2019-05-15 02:55
I find a ml-agents folder in \Reinforcement-Learning-With-Unity-G.E.A.R-master\ml-agents
It's already in the folder, do you mean this one?
and ml-agents are updated, which version are you using?

**Comment by vxgu86** [comment] 2019-05-15 02:56
or do you mean this:
Reinforcement-Learning-With-Unity-G.E.A.R-master\unity-environment\unity-environment\gear-unity\Assets\ML-Agents

**Comment by dtransposed** [comment] 2019-05-16 15:02
You should replace the ml-agents installed in your virtual environment (.../lib/site-packages/ml-agents/ ) with Reinforcement-Learning-With-Unity-G.E.A.R-master\ml-agents.

**Comment by vxgu86** [comment] 2019-06-06 10:15
I installed as followed, but found no ml-agents/ in the lib/site-packages/, none in envs/ml-agents either.

Installing for Development
If you intend to make modifications to ml-agents or ml-agents-envs, you should install the packages from the cloned repo rather than from PyPi. To do this, you will need to install ml-agents and ml-agents-envs separately.

In our example, the files are located in C:\Downloads. After you have either cloned or downloaded the files, from the Anaconda Prompt, change to the ml-agents subdirectory inside the ml-agents directory:

cd C:\Downloads\ml-agents
From the repo's main directory, now run:

cd ml-agents-envs
pip install -e .
cd ..
cd ml-agents
pip install -e .

should I do this one :   pip install mlagents

**Comment by dtransposed** [comment] 2019-06-11 16:57
This is a correct part of the instruction from Unity repo. Installing ML-Toolkit according to the official instructions by Unity additionally involves creating python virtual environment. This is the recommended step, please do so. Then you can do the operations described above.
